### ISSUE TITLE
'RemovedInDjango20Warning' import error

### ISSUE THREAD

**Issue by florinpapa** [r4fek/django-cassandra-engine#107]
Hello,

I am trying to run "django-admin setup", but I get this error:
```
$ django-admin setup
Traceback (most recent call last):
  File "/home/florin/venv_py352/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django_cassandra_engine/apps.py", line 63, in import_models
    return super(AppConfig, self).import_models(*args, **kwargs)
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/florin/django_wl/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django_cassandra_engine/models/__init__.py", line 22, in <module>
    from . import django_field_methods
  File "/home/florin/venv_py352/lib/python3.5/site-packages/django_cassandra_engine/models/django_field_methods.py", line 10, in <module>
    from django.utils.deprecation import RemovedInDjango20Warning
ImportError: cannot import name 'RemovedInDjango20Warning'
```
I am using django-cassandra-engine-1.3.0 and Django 2.0.

I see that the name of this class that fails to be imported changes with the Django version, while the "RemovedInNextVersionWarning" stays the same in django/utils/deprecation.py. Would a PR that changes the name "RemovedInDjango20Warning" to "RemovedInNextVersionWarning" be acceptable?

**Comment by mosight** [comment]
Hey @r4fek . Is this under your radar? Looking forward to the resolution of this. Thanks a lot!

**Comment by r4fek** [comment]
Hey @mosight and @florinpapa,

Please take a look at current 1.4 version. This should be fixed now.
