### ISSUE TITLE
Problems with list and set fields in Django

### ISSUE THREAD

**Issue by Micky87** [r4fek/django-cassandra-engine#37]
started few days ago to use Cassandra and Django, so I'm a newbie.

My model's code works well and creates all tables in my db until I add List a field(language in this case)
    import uuid
    from cassandra.cqlengine import columns
    from cassandra.cqlengine.models import Model    
```python
    class User(Model):
        id = columns.UUID(primary_key=True, default=uuid.uuid4)
        username = columns.Text(max_length=30, required=True)
        password = columns.Text(max_length=55, required=True)
        position = columns.Text(max_length=9)
        gender = columns.UUID()
        status = columns.UUID()
        languages = columns.List(value_type=uuid, default=list)
        profile_image = columns.Text(max_length=255)

    class Language(Model):
        id = columns.UUID(primary_key=True, default=uuid.uuid4)
        gender = columns.Text(max_length=20) 
```
After running python "manage.py sync_cassandra"
I receive the following error:

```
 Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/federico/Progetti/Tutorial/Django/HelloWorld/helloworld/tutorial/models.py", line 6, in <module>
    class User(Model):
  File "/home/federico/Progetti/Tutorial/Django/HelloWorld/helloworld/tutorial/models.py", line 13, in User
    languages = columns.List(value_type=uuid, default='list')
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/columns.py", line 765, in __init__
    self.db_type = 'list<{}>'.format(value_type.db_type)
AttributeError: 'module' object has no attribute 'db_type'
federico@federico-VirtualBox:~/Progetti/Tutorial/Django/HelloWorld/helloworld$ python manage.py sync_cassandra
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
federico@federico-VirtualBox:~/Progetti/Tutorial/Django/HelloWorld/helloworld$ python manage.py sync_cassandra
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/federico/Progetti/Tutorial/Django/HelloWorld/helloworld/tutorial/models.py", line 6, in <module>
    class User(Model):
  File "/home/federico/Progetti/Tutorial/Django/HelloWorld/helloworld/tutorial/models.py", line 13, in User
    languages = columns.List(value_type=uuid, default=list)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/columns.py", line 765, in __init__
    self.db_type = 'list<{}>'.format(value_type.db_type)
AttributeError: 'module' object has no attribute 'db_type'
```

**Comment by r4fek** [comment]
Hi @Micky87,

Your error is talking to you, just read it :)
Look at this line
    
    languages = columns.List(value_type=uuid, default=list)

you're misusing `columns.List` field. 

I think it should look like this (I might be wrong though):

    languages = columns.List(value_type=columns.UUID, default=list)

I would like you to refer you to documentation https://cqlengine.readthedocs.org/en/latest/topics/columns.html

I hope this helps.

**Comment by Micky87** [comment]
Thank you very much, now I also understand better how it works!
