### ISSUE TITLE
NoHostAvailable exception

### ISSUE THREAD

**Issue by chesslemon** [r4fek/django-cassandra-engine#46]
Hi, I am having some problem when running Django through `coverage.py` as follows:

```
$ coverage run manage.py shell
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/virtualenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/virtualenv/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/virtualenv/lib/python2.7/site-packages/django_cassandra_engine/models.py", line 12, in <module>
    cassandra_connection.connect()
  File "/virtualenv/lib/python2.7/site-packages/django_cassandra_engine/base/__init__.py", line 94, in connect
    self.connection = CassandraConnection(**settings)
  File "/virtualenv/lib/python2.7/site-packages/django_cassandra_engine/connection.py", line 53, in __init__
    self.setup()
  File "/virtualenv/lib/python2.7/site-packages/django_cassandra_engine/connection.py", line 60, in setup
    connection.setup(self.hosts, self.keyspace, **self.connection_options)
  File "/virtualenv/lib/python2.7/site-packages/cassandra/cqlengine/connection.py", line 131, in setup
    session = cluster.connect()
  File "cassandra/cluster.py", line 820, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:11444)
    with self._lock:
  File "cassandra/cluster.py", line 846, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:11266)
    raise
  File "cassandra/cluster.py", line 840, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:11146)
    self.control_connection.connect()
  File "cassandra/cluster.py", line 2088, in cassandra.cluster.ControlConnection.connect (cassandra/cluster.c:36955)
    self._set_new_connection(self._reconnect_internal())
  File "cassandra/cluster.py", line 2123, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:37811)
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1': OperationTimedOut('errors=Timed out creating connection (5 seconds), last_host=None',)})
```

If I run the same command without coverage.py the exception does not raises and the tests just goes fine. I've tested with `manage.py test, manage.py shell and manage.py runserver`

Can you help me?
Thanks!

**Comment by chesslemon** [comment]
I think is is related to threading contexts issues, maybe it is related to this or one of it's references: https://datastax-oss.atlassian.net/browse/PYTHON-224

However, I still don't know how to solve this issue.
