### ISSUE TITLE
Django admin not working with cassandra db engine

### ISSUE THREAD

**Issue by filipnovotny** [r4fek/django-cassandra-engine#51]
Hello,

with cassandra as the only db engine and django 1.9 on python 3.5, I have the following error when accessing django_admin:

`NotImplementedError at /admin/login/`
subclasses of BaseDatabaseOperations may require a quote_name() method

if I add that method to operations.py, I have another bug in __init__.py in __getattr__:
`        raise AttributeError(attr)` ... with attr='operators'

Isn't the cassandra engine supposed to work with django-admin?

Thank you!

**Comment by r4fek** [comment]
I'll fix it in next version. Thanks for the report!

**Comment by nirkra** [comment]
Any news regarding this issue ?

**Comment by r4fek** [comment]
@nirkra you shouldn't get this error on the latest version of dce.

**Comment by darleybarreto** [comment]
@r4fek I'm a newbie on django programming, so I dont know if I am doing it right, but I'm receiving the same error. Regards.

**Comment by r4fek** [comment]
Please try now. Make sure that all your cassandra models inherit from `django_cassandra_engine.models.DjangoCassandraModel`.

**Comment by supbhatt** [comment]
Hi,

I have tried to create a super user for Cassandra django admin. However, I am getting the same NotImplementedError.
The error says "NotImplementedError : Method not available on Cassandra model fields

I am using python version 2.7.13 and django version 1.10.5

**Comment by wangzhe3224** [comment]
Hi, I used following example model in django admin page: 

`class ExampleModel(DjangoCassandraModel):
    example_id    = columns.UUID(primary_key=True, default=uuid.uuid4)
    example_type  = columns.Integer(index=True)
    created_at    = columns.DateTime()
    description   = columns.Text(required=False)`

But when I try to add row into it I got following error:

`    return datetime.utcfromtimestamp(value)
TypeError: an integer is required (got type str)`

I think the front end passed a string instead of int to the mode. 

Could someone help me with this? Thanks a lot!

Regards,
Zhe

**Comment by Joojoo1020** [comment]
is createsuperuser  working now??

**Comment by swamirara** [comment]
any updates on the ccreatesuperuser ?

**Comment by sauravsavarn** [comment]
Hi, Please suggest

In my django project , i have a cassandra database as defined in settings.py also created model say Interview using DjangoCassandraModel.

Attached the model and settings file. Now when i register this model to admin.py and running using python manage.py runserver giving no error but when try to launch admin giving error now as :

**ERROR:**

(venv) (base) Sauravs-MBP:pronnati spartans$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 29, 2020 - 09:27:22
Django version 3.1.2, using settings 'pronnati.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/apps/registry.py", line 156, in get_app_config
    return self.app_configs[app_label]
KeyError: 'interview'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 251, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 502, in index
    app_list = self.get_app_list(request)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 485, in get_app_list
    app_dict = self._build_app_dict(request)
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 465, in _build_app_dict
    'name': apps.get_app_config(app_label).verbose_name,
  File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/apps/registry.py", line 163, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'interview'.
[29/Oct/2020 09:28:01] "GET /admin/ HTTP/1.1" 500 112148



** Attachment with .txt added to python file for sharing purpose**

[settings.py.txt](https://github.com/r4fek/django-cassandra-engine/files/5457384/settings.py.txt)
[admin.py.txt](https://github.com/r4fek/django-cassandra-engine/files/5457387/admin.py.txt)
[models.py.txt](https://github.com/r4fek/django-cassandra-engine/files/5457391/models.py.txt)

**Comment by harisrinivaas** [comment]
> Hi, Please suggest
> 
> In my django project , i have a cassandra database as defined in settings.py also created model say Interview using DjangoCassandraModel.
> 
> Attached the model and settings file. Now when i register this model to admin.py and running using python manage.py runserver giving no error but when try to launch admin giving error now as :
> 
> **ERROR:**
> 
> (venv) (base) Sauravs-MBP:pronnati spartans$ python manage.py runserver
> Watching for file changes with StatReloader
> Performing system checks...
> 
> System check identified no issues (0 silenced).
> October 29, 2020 - 09:27:22
> Django version 3.1.2, using settings 'pronnati.settings'
> Starting development server at http://127.0.0.1:8000/
> Quit the server with CONTROL-C.
> Internal Server Error: /admin/
> Traceback (most recent call last):
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/apps/registry.py", line 156, in get_app_config
> return self.app_configs[app_label]
> KeyError: 'interview'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
> response = get_response(request)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 251, in wrapper
> return self.admin_view(view, cacheable)(*args, **kwargs)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
> response = view_func(request, *args, **kwargs)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
> response = view_func(request, *args, **kwargs)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 233, in inner
> return view(request, *args, **kwargs)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
> response = view_func(request, *args, **kwargs)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 502, in index
> app_list = self.get_app_list(request)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 485, in get_app_list
> app_dict = self._build_app_dict(request)
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 465, in _build_app_dict
> 'name': apps.get_app_config(app_label).verbose_name,
> File "/Volumes/Macintosh-USER HD/workspace/workspace_django/microfinance/venv/lib/python3.9/site-packages/django/apps/registry.py", line 163, in get_app_config
> raise LookupError(message)
> LookupError: No installed app with label 'interview'.
> [29/Oct/2020 09:28:01] "GET /admin/ HTTP/1.1" 500 112148
> 
> ** Attachment with .txt added to python file for sharing purpose**
> 
> [settings.py.txt](https://github.com/r4fek/django-cassandra-engine/files/5457384/settings.py.txt)
> [admin.py.txt](https://github.com/r4fek/django-cassandra-engine/files/5457387/admin.py.txt)
> [models.py.txt](https://github.com/r4fek/django-cassandra-engine/files/5457391/models.py.txt)

**Comment by harisrinivaas** [comment]
Cassandra doesn't support django-admin at the moment.

**Comment by sauravsavarn** [comment]
> Cassandra doesn't support django-admin at the moment.

Thanks Hari!!

**Comment by amanrawat121** [comment]
> is createsuperuser  working now??

Did it working for you now??

**Comment by amanrawat121** [comment]
> any updates on the ccreatesuperuser ?
> 

I m currently working on it. Did that worked for you??

**Comment by tekintopuz** [comment]
Is it working now???
