### ISSUE TITLE
sync_cassandra issue with cassandra docker image 3.5

### ISSUE THREAD

**Issue by grillazz** [r4fek/django-cassandra-engine#68]
Hi,

I have below error when trying sync_cassandra with docker cassandra image 3.5

However my models are created with success.

Thanks,

J

```python
(cass)jj@jj-box:~/projects_dev/cass_projects$ sudo docker-compose run web python manage.py sync_cassandra
/usr/local/lib/python3.5/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
  RemovedInDjango110Warning

/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

Creating keyspace db..
/usr/local/lib/python3.5/site-packages/cassandra/cqlengine/management.py:462: UserWarning: CQLENG_ALLOW_SCHEMA_MANAGEMENT environment variable is not set. Future versions of this package will require this variable to enable management functions.
  warnings.warn(msg)

Syncing kaska.models.UserGuess
Syncing kaska.models.UserLike
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python3.5/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 116, in handle_noargs
    emit_post_migrate_signal(1, False, cassandra_alias)
  File "/usr/local/lib/python3.5/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 29, in emit_post_migrate_signal
    using=db)
  File "/usr/local/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/management/__init__.py", line 85, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/contenttypes/models.py", line 67, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 837, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 389, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 366, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/where.py", line 79, in as_sql
    sql, params = compiler.compile(child)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 366, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/lookups.py", line 160, in as_sql
    rhs_sql = self.get_rhs_op(connection, rhs_sql)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/lookups.py", line 164, in get_rhs_op
    return connection.operators[self.lookup_name] % rhs
  File "/usr/local/lib/python3.5/site-packages/django_cassandra_engine/base/__init__.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: operators
```
Please find my `requirements.txt` file below.

```
Django==1.9.7
djangorestframework
django-cassandra-engine
wheel==0.24.0
```

**Comment by deliro** [comment]
Same issue while working under Vagrant:
`(dce)vagrant@vagrant-ubuntu-trusty-64:~/dcecode$ python manage.py sync_cassandra
/home/vagrant/dce/lib/python3.4/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
  RemovedInDjango110Warning

/home/vagrant/dce/lib/python3.4/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

Creating keyspace db..
/home/vagrant/dce/lib/python3.4/site-packages/cassandra/cqlengine/management.py:462: UserWarning: CQLENG_ALLOW_SCHEMA_MANAGEMENT environment variable is not set. Future versions of this package will require this variable to enable management functions.
  warnings.warn(msg)

Syncing core.models.Car
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 116, in handle_noargs
    emit_post_migrate_signal(1, False, cassandra_alias)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 29, in emit_post_migrate_signal
    using=db)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/contrib/auth/management/__init__.py", line 85, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/contrib/contenttypes/models.py", line 67, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 837, in execute_sql
    sql, params = self.as_sql()
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 389, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 366, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/sql/where.py", line 79, in as_sql
    sql, params = compiler.compile(child)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 366, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/lookups.py", line 160, in as_sql
    rhs_sql = self.get_rhs_op(connection, rhs_sql)
  File "/home/vagrant/dce/lib/python3.4/site-packages/django/db/models/lookups.py", line 164, in get_rhs_op
    return connection.operators[self.lookup_name] % rhs
  File "/home/vagrant/dce/lib/python3.4/site-packages/django_cassandra_engine/base/__init__.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: operators
`

requirements.txt is
django==1.9.7
django-cassandra-engine==0.10.0

**Comment by belgacea** [comment]
+1
Same issue, same requirement as @deliro but under windows 10 (sry) and models don't sync..

**Comment by r4fek** [comment]
It happens because you guys have `django.contrib.auth` app on `INSTALLED_APPS` list and `django_cassandra_engine` is your default database backend. Please use relational database as default and cassandra as secondary.

**Comment by belgacea** [comment]
I tried to set sqlite as default and cassandra as secondary but I still get the same error. Is there something else to do ?
Also if cassandra must be defined as secondary, can you please update the read me ?
Thanks

**Comment by alieblice** [comment]
Hi 
i did put cassandra as second database but steel i have same problem :
`Creating keyspace db..
/usr/local/lib/python3.5/dist-packages/cassandra/cqlengine/management.py:492: UserWarning: CQLENG_ALLOW_SCHEMA_MANAGEMENT environment variable is not set. Future versions of this package will require this variable to enable management functions.
  warnings.warn(msg)
`

i attached my settings.py  
i used exact example in installation guide

[settings.py.txt](https://github.com/r4fek/django-cassandra-engine/files/423038/settings.py.txt)

here is my django version :
`django-admin --version
1.9.7
`
best regard

**Comment by r4fek** [comment]
@alieblice have you tried version with latest fix?

**Comment by grillazz** [comment]
@alieblice try `python manage.py sync_cassandra --database cassandra` you need to spec database name

**Comment by alieblice** [comment]
@r4fek thanks for replying
 after you sayed latest version i downloaded zip file from github and upgraded to it with this command :
`$ sudo pip3 install --upgrade --no-index --find-links=file:./ django-cassandra-engine-master.zip `

the out put of the error changed but steel same error at the beginning lines:

`$ python3 manage.py syncdb
Creating keyspace db..
/usr/local/lib/python3.5/dist-packages/cassandra/cqlengine/management.py:492: UserWarning: CQLENG_ALLOW_SCHEMA_MANAGEMENT environment variable is not set. Future versions of this package will require this variable to enable management functions.
  warnings.warn(msg)
Syncing books.models.ExampleModel
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django_cassandra_engine/management/commands/syncdb.py", line 26, in handle
    return super(Command, self).handle(**options)
  File "/usr/local/lib/python3.5/dist-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 126, in handle
    emit_post_migrate_signal(1, False, cassandra_alias)
  File "/usr/local/lib/python3.5/dist-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 36, in emit_post_migrate_signal
    using=db)
  File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/management/__init__.py", line 63, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/contenttypes/models.py", line 52, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1085, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django_cassandra_engine/utils.py", line 47, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django_cassandra_engine/connection.py", line 13, in execute
    return self.connection.execute(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django_cassandra_engine/connection.py", line 85, in execute
    return self.session.execute(qs, *args, **kwargs)
  File "cassandra/cluster.py", line 1961, in cassandra.cluster.Session.execute (cassandra/cluster.c:34076)
  File "cassandra/cluster.py", line 3649, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:69755)
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:139 no viable alternative at input '.' (...django_content_type.model FROM django_content_type WHERE [(]django_content_type....)">
`

**Comment by alieblice** [comment]
@grillazz 
i steel get same error :

`$ python3 manage.py sync_cassandra --database cassandra
Creating keyspace db..
/usr/local/lib/python3.5/dist-packages/cassandra/cqlengine/management.py:492: UserWarning: CQLENG_ALLOW_SCHEMA_MANAGEMENT environment variable is not set. Future versions of this package will require this variable to enable management functions.
  warnings.warn(msg)
Syncing books.models.ExampleModel
`

**Comment by r4fek** [comment]
@alieblice I don't see any error in your latest traceback. Your ExampleModel was synced correctly

**Comment by alieblice** [comment]
@r4fek 
you'r right , sorry for that , i should pay more attention to the output
i checked with _cqlsh_  command and table was there
thanks

**Comment by grillazz** [comment]
@alieblice please find below `Dockerfile` which will solving this warning
```docker
FROM python:3.5

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/
ENV CQLENG_ALLOW_SCHEMA_MANAGEMENT="True"
```

**Comment by pavank8123** [comment]
Hi @r4fek 

I am following this package for django-casandra integration [here](http://r4fek.github.io/django-cassandra-engine/guide/tests/).

I want use only casandra database as default. If I don't specify other database then running `sync_cassandra` raises `AttributeError: operators`. 

If I specify other(sqlite) database then all django auth tables and permission tables are created in sqlite. I want everything in casandra.
