### ISSUE TITLE
AttributeError: operators

### ISSUE THREAD

**Issue by dhararon** [r4fek/django-cassandra-engine#70]
Hi,  Always when i run 
```python
python manage.py sync_cassandra
```
return this exception
```bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 116, in handle_noargs
    emit_post_migrate_signal(1, False, cassandra_alias)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 29, in emit_post_migrate_signal
    using=db)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 85, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 67, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 837, in execute_sql
    sql, params = self.as_sql()
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 389, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 366, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/sql/where.py", line 79, in as_sql
    sql, params = compiler.compile(child)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 366, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/lookups.py", line 160, in as_sql
    rhs_sql = self.get_rhs_op(connection, rhs_sql)
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django/db/models/lookups.py", line 164, in get_rhs_op
    return connection.operators[self.lookup_name] % rhs
  File "/Users/dhararon/.virtualenvs/rocket_backend/lib/python2.7/site-packages/django_cassandra_engine/base/__init__.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: operators
```
I think this is happen because and the process.

**Comment by sfyx** [comment]
A dirty and improper solution is to comment out emit_post_migrate_signal (sync_cassandra.py, line 29)
