### ISSUE TITLE
Update on models

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [r4fek/django-cassandra-engine#77]
The issue is changing the primary key on the models.py

from:

      class SamplePartitioning(Model):
        id_1 = columns.Integer(partition_key=True)
        id_2 = columns.Text(primary_key=True)
        id_3 = columns.Integer(primary_key=True)

to:

      class SamplePartitioning(Model):
        id_1 = columns.Integer(partition_key=True)
        id_2 = columns.Text()
        id_3 = columns.Integer()

And when I run sync_cassandra. I got this error:

      Traceback (most recent call last):
        File "manage.py", line 10, in <module>
          execute_from_command_line(sys.argv)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
          utility.execute()
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
          self.fetch_command(subcommand).run_from_argv(self.argv)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
          self.execute(*args, **cmd_options)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
          output = self.handle(*args, **options)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 98, in handle
          self.sync(alias)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 85, in sync
          sync_table(model)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/cassandra/cqlengine/management.py", line 149, in sync_table
          _sync_table(model)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/cassandra/cqlengine/management.py", line 199, in _sync_table
          _validate_pk(model, table_meta)
        File "/Users/deanarmada/.virtualenvs/django-cassandra/lib/python2.7/site-packages/cassandra/cqlengine/management.py", line 259, in _validate_pk
          _pk_string(meta_partition, meta_clustering)))
      cassandra.cqlengine.CQLEngineException: Model <class 'example.models.SamplePartitioning'> PRIMARY KEY composition does not match existing table db.sample_partitioning. Model: PRIMARY KEY ((id_1)); Table: PRIMARY KEY ((id_1), id_2, id_3). Update model or drop the table.

I also updating by just adding another column from:

	class SamplePartitioning(Model):
		id_1 = columns.Integer(partition_key=True)
		id_2 = columns.Text(primary_key=True)
		id_3 = columns.Integer(primary_key=True)
		name = columns.Text()

to:

	class SamplePartitioning(Model):
		id_1 = columns.Integer(partition_key=True)
		id_2 = columns.Text(primary_key=True)
		id_3 = columns.Integer(primary_key=True)
		player_name = columns.Text()

And I got this when I described my table:

	CREATE TABLE db.sample_partitioning (
	    id_1 int,
	    id_2 text,
	    id_3 int,
	    name text,
	    player_name text,
	    PRIMARY KEY (id_1, id_2, id_3)
	) WITH CLUSTERING ORDER BY (id_2 ASC, id_3 ASC)

My column name is still there?

I am experimenting on things and I would like to raise this to know if this is a bug or there is a standard way of doing this.. Because the only way that I know is using the drop_table() on the shell and creating the model again

**Comment by r4fek** [comment]
Unfortunately this is how it works. Removing column from your code does not remove column from the database. You have to do it on your own. Also changing PK's it's not possible. This is how Cassandra works and we can't do much about it. `sync_cassandra` only adds new columns and models to the schema.

**Comment by Dean-Christian-Armada** [comment]
Thanks for the answer!
