### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by kyloy** [r4fek/django-cassandra-engine#83]
i got this issues when i try to sync my DB in the comman line i use
./manage.py syncdb

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django_cassandra_engine/apps.py", line 65, in ready
    conn.connect()
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django_cassandra_engine/base/__init__.py", line 104, in connect
    self.connection = CassandraConnection(**settings)
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django_cassandra_engine/connection.py", line 58, in __init__
    self.setup()
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/django_cassandra_engine/connection.py", line 73, in setup
    **self.connection_options)
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/cassandra/cqlengine/connection.py", line 267, in setup
    retry_connect=retry_connect, cluster_options=kwargs, default=True)
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/cassandra/cqlengine/connection.py", line 149, in register_connection
    conn.setup()
  File "/home/kyloy/Cassandra/lib/python2.7/site-packages/cassandra/cqlengine/connection.py", line 94, in setup
    self.cluster = Cluster(self.hosts, **self.cluster_options)
  File "cassandra/cluster.py", line 792, in cassandra.cluster.Cluster.__init__ (cassandra/cluster.c:10688)
socket.gaierror: [Errno -2] Name or service not known

**Comment by r4fek** [comment]
Please make sure that Cassandra is running and you provided valid credentials if needed.

**Comment by kyloy** [comment]
sorry i'm new on this, how can i check that?
i am already running my environment, should i run the server too? and in other command line run the sync_cassandra?
